apiVersion: privatecloud.mendix.com/v1alpha1
kind: MendixApp
metadata:
  name: standalone1
  namespace: mxconnector
spec:
  allowOverrideSecretsWithSecretStoreCSIDriver: false
  appURL: 
  database:
    servicePlan: mxpostgre
  mendixRuntimeVersion: 10.1.1.12532
  replicas: 2
  resources:
    limits:
      cpu: '1'
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
  runtime:
    customConfiguration: >-
      {"ScheduledEventExecution":"NONE","MicroflowConstants":"{\"AmazonS3Connector.AccessKeyID\":\"AKIAZBM2K5BAIKBIX3VZ\",\"AmazonS3Connector.ClientCertificateID\":\"\",\"AmazonS3Connector.Duration\":\"0\",\"AmazonS3Connector.ProfileARN\":\"\",\"AmazonS3Connector.RoleARN\":\"\",\"AmazonS3Connector.SecretAccessKey\":\"EXF1HDOh4hp6FycXnd8Paj5Sw/3ZzZH6t3pAVY2m\",\"AmazonS3Connector.SessionName\":\"\",\"AmazonS3Connector.TrustAnchorARN\":\"\",\"AmazonS3Connector.UseStaticCredentials\":\"True\",\"AmazonS3Connector.Version\":\"2.0.1\",\"CommunityCommons.MergeMultiplePdfs_MaxAtOnce\":\"10\",\"Encryption.EncryptionKey\":\"12345678901234567890123456789012\",\"Encryption.EncryptionPrefix\":\"{AES3}\",\"Encryption.LegacyEncryptionKey\":\"\",\"Encryption.LogNode\":\"Encryption\",\"MicrosoftGraph.GraphLocation\":\"https://graph.microsoft.com/v1.0\",\"MicrosoftGraph.LoginLocation\":\"https://login.microsoftonline.com\",\"MicrosoftGraph.LogNode\":\"Microsoft
      Graph\",\"MicrosoftGraph.MicrosoftGraphConnector_Version\":\"3.0.2\",\"MicrosoftGraph.ProxyHost\":\"\",\"MicrosoftGraph.ProxyPort\":\"0\",\"MicrosoftGraph_Applications.LogNode\":\"Microsoft
      Graph\",\"MicrosoftGraph_Applications.MicrosoftGraphApplications_Version\":\"1.0.0\",\"MicrosoftGraph_Outlook.LogNode\":\"Microsoft
      Graph
      Outlook\",\"MicrosoftGraph_Outlook.MicrosoftGraphConnector_Version\":\"1.0.0\",\"NanoflowCommons.Nanoflow_Commons_Version\":\"4.0.0\"}","License.EnvironmentName":"e608d604-c148-4185-94bc-d1aba82ae604"}
    dtapMode: D
    logAutosubscribeLevel: INFO
    mxAdminPassword: QWJjQDEyMzQ1Njc4
    debuggerPassword: QWJjQDEyMzQ1Njc4
    runtimeLicense: {}
  runtimeMetricsConfiguration: {}
  sourceURL: >-
    https://package-store-prod-2.s3-accelerate.amazonaws.com/c6bae8ec-220c-41f5-8014-f91c50cc8284/56caf0e8b0bef78f8f09f4a946526cab/main-0.1.0.905b1d6e.mda?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAXYS2GLE2BQXUZIJY%2F20240514%2Feu-central-1%2Fs3%2Faws4_request&X-Amz-Date=20240514T101044Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=1ebe4c6b03916846f9b654379f0a35eb470eec96ce36a007b6f584a721830f9a 
  storage:
    servicePlan: mendixblob

